# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-02-14 12:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=128)),
                ('driver_phone', models.CharField(max_length=10)),
                ('driver_vehicle_model', models.CharField(max_length=128)),
                ('driver_vehicle_number', models.CharField(max_length=10)),
                ('driver_password', models.CharField(max_length=32)),
                ('driver_city', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_city', models.CharField(max_length=64)),
                ('person_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ride_overspeedcount', models.IntegerField(default=0)),
                ('ride_datetime', models.DateTimeField(auto_now_add=True)),
                ('ride_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='RideData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ridedata_speed', models.IntegerField(default=-1)),
                ('ridedata_location', models.CharField(max_length=128)),
                ('ridedata_datetime', models.DateTimeField(auto_now_add=True)),
                ('ridedata_ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Ride')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Person'),
        ),
    ]
